services:
  alumni-server:
    build: ./backEnd
    container_name: alumniBE
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}

    labels:
      - traefik.enable=true
      - traefik.http.routers.alumni-server-router.rule=Host(api.fgckwali-alumni.org)
      - traefik.http.routers.alumni-server-router.tls=true
      - traefik.http.routers.alumni-server-router.tls.certresolver=myresolver
      - traefik.http.routers.alumni-server-router.middlewares=https-redirect@docker
      - traefik.http.services.alumni-server.loadbalancer.server.port=3000
      - traefik.http.routers.alumni-server-http-to-https.rule=Host(api.fgckwali-alumni.org)
      - traefik.http.routers.alumni-server-http-to-https.entrypoints=web
      - traefik.http.routers.alumni-server-http-to-https.middlewares=https-redirect
    networks:
      - ddld-net
  # alumni-web:
  #   build: ./frontEnd
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.alumni-web-router.rule=Host(fgckwali-alumni.org)
  #     - traefik.http.routers.alumni-web-router.tls=true
  #     - traefik.http.routers.alumni-web-router.tls.certresolver=myresolver
  #     - traefik.http.routers.alumni-web-router.middlewares=https-redirect@docker
  #     - traefik.http.services.alumni-web.loadbalancer.server.port=80
  #     - traefik.http.routers.alumni-web-http-to-https.rule=Host(fgckwali-alumni.org)
  #     - traefik.http.routers.alumni-web-http-to-https.entrypoints=web
  #     - traefik.http.routers.alumni-web-http-to-https.middlewares=https-redirect
  #   networks:
  #     - ddld-net
networks:
  ddld-net:
    external: true
